version: "2"
services:
  backend:
    container_name: backend
    build: ./backend
    # volumes:
    #    - ./backend:/usr/src/app/backend
    #    - /usr/src/app/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  # frontend:
  #   container_name: frontend
  #   restart: always
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Zaq12wsx!
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"